using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShivamFinlytics.Application.DTOs;
using ShivamFinlytics.Application.Interfaces;

namespace ShivamFinlytyics.API.Controllers;

/// <summary>
/// Manages financial insights and advisory content generated by analysts.
/// </summary>
[Route("api/[controller]")]
[ApiController]
public class InsightController : ControllerBase
{
    private readonly IInsightService _service;

    public InsightController(IInsightService service)
    {
        _service = service;
    }

    /// <summary>
    /// Creates a new financial insight.
    /// Restricted to Users with 'Analyst' or 'Admin' roles.
    /// </summary>
    /// <param name="dto">The data transfer object for the new insight.</param>
    /// <returns>A success message if created; otherwise, an authorization or validation error.</returns>
    [Authorize(Roles = "Analyst,Admin")]
    [HttpPost("Create")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> Create([FromBody] CreateInsightDto dto)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier) ?? User.FindFirst("id");

        if (userIdClaim == null)
        {
            return Unauthorized(new { message = "User ID not found in token." });
        }

        if (!int.TryParse(userIdClaim.Value, out int userId))
        {
            return BadRequest(new { message = "Invalid User ID format in token." });
        }

        await _service.CreateInsight(dto, userId);
        return Ok(new { message = "Insight created successfully" });
    }

    /// <summary>
    /// Retrieves all available financial insights.
    /// </summary>
    /// <returns>A list of financial insights.</returns>
    [Authorize]
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<IActionResult> GetAll()
    {
        var data = await _service.GetAll();
        return Ok(data);
    }
}